-- Script para Supabase SQL Editor (PostgreSQL)

-- Tabla para las reservas
create table if not exists bookings (
    id text primary key,
    client_name text not null,
    phone text not null,
    total_price bigint not null,
    date date not null,
    time text not null,
    status text default 'recibida' check (status in ('recibida', 'realizada', 'no-asistio', 'cancelada')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla para los servicios de cada reserva
create table if not exists booking_services (
    id bigint generated by default as identity primary key,
    booking_id text references bookings(id) on delete cascade not null,
    service_id text not null,
    service_name text not null,
    service_price bigint not null
);

-- Habilitar seguridad de nivel de fila (Opcional pero recomendado)
alter table bookings enable row level security;
alter table booking_services enable row level security;

-- Políticas de acceso público para insertar (Reservas desde la web)
create policy "Cualquiera puede crear reservas" on bookings for insert with check (true);
create policy "Cualquiera puede crear servicios de reserva" on booking_services for insert with check (true);

-- Políticas de lectura para el Admin (Requiere configurar auth después, o acceso total por ahora)
create policy "Acceso total para lectura" on bookings for select using (true);
create policy "Acceso total para lectura servicios" on booking_services for select using (true);
